---
roles:
  - src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.11.0"
    name: clickhouse

  - src: git@github.com:udjin10/vector-role.git
    scm: git
    version: "1.0.4"
    name: vector

  - src: git@github.com:udjin10/lighthouse_role.git
    scm: git
    version: "1.0.2"
    name: lighthouse
