---

- name: install bundle(click vector )
  hosts:
    - clickhouse-01
  become: true
  roles:
    - role: clickhouse
    - role: vector

- name: install bundle(lighthouse nginx)
  hosts:
    - lighthouse-01
  become: true
  roles:
    - role: lighthouse
