---


all:
  hosts:
    clickhouse-01:
      ansible_host: 127.0.0.1
      host_vars:

        clickhouse_version: "22.3.3.44"
        clickhouse_packages:
          - clickhouse-client
          - clickhouse-server
          - clickhouse-common-static
        vector_version: "0.22.3"
        ansible_connection: ssh
        ansible_user: udjin
        ansible_ssh_private_key_file: /home/udjin/.ssh/id_ed25519